# Generated by Django 3.1.7 on 2021-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('createAt', models.DateTimeField()),
                ('logoutAt', models.DateTimeField()),
                ('lastLogin', models.DateTimeField()),
                ('items_puchased', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('createAt', models.DateTimeField()),
                ('logoutAt', models.DateTimeField()),
                ('lastLogin', models.DateTimeField()),
            ],
        ),
    ]
