# Generated by Django 3.1.7 on 2021-02-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastLogin', models.DateField()),
                ('lastlogout', models.DateField()),
                ('profilePhoto', models.BooleanField(default=False)),
                ('eventAndMarketing', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('personDetails', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(default='01082930455', max_length=20)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('lastLogin', models.DateField()),
                ('lastlogout', models.DateField()),
                ('profilePhoto', models.BooleanField(default=False)),
                ('eventAndMarketing', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('personDetails', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal', models.TextField()),
                ('profilePhoto', models.TextField()),
                ('eventAndMarketing', models.TextField()),
                ('service', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemPurchased',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('purchasedAt', models.DateField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller')),
            ],
        ),
    ]
