# Generated by Django 3.1.7 on 2021-02-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsandcondition',
            old_name='eventAndMarketing',
            new_name='conditions',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='profilePhoto',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='service',
        ),
    ]
